//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_RESTAURANT
    {
        public int Id { get; set; }
        public string Restaurant_Name { get; set; }
        public string Location { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public string City { get; set; }
        public string Cuisine { get; set; }
    }
}
