//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class demoCaseStudyApiEntities : DbContext
    {
        public demoCaseStudyApiEntities()
            : base("name=demoCaseStudyApiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_RESTAURANT> M_RESTAURANT { get; set; }
        public virtual DbSet<M_REVIEW> M_REVIEW { get; set; }
    }
}
